import = ["/home/mirzaahmedov/.config/alacritty/themes/solarized_dark.toml"]

[cursor]
blink_interval = 750

[cursor.style]
blinking = "Always"

[font]
size = 18

[font.normal]
family = "Source Code Pro"

[shell]
program = "/bin/zsh"

[window]
opacity = 1.0

[window.padding]
x = 10
y = 0
